---
- name: create dirs
  file:
    path: "{{ item.dst_dir }}"
    state: directory
    mode: "0755"
  loop: "{{ pushgateway_functions_files }}"

- name: download library
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dst_dir }}/{{ item.name }}"
    mode: "{{ item.mode }}"
    checksum: "{{ item.chksum }}"
  loop: "{{ pushgateway_functions_files }}"
  when: not ansible_check_mode
